[package]
name = "example-wasm"
version = "0.1.0"
description = "Workflow Allocator Example WASM Bindings"
license = "MIT/Apache-2.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]

kaizen = { path = "../../kaizen" }
example = { path = "../lib" }
