[package]
name = "example-program"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
solana-program = "1.14.1"
example = { path = "../lib" }
# borsh = "0.9.3"
# serde_json = "1.0.83"
